name: Sync

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:zzzsyyy/zzzsyyy.github.io.git
          destination-repo: git@gitee.com:zzzsyyy/zzzsyyy.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: zzzsyyy
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: zzzsyyy/zzzsyyy
          branch: main
